require("plugins.handmade.fuzzy_tabs")
require("plugins.handmade.bufferize")
require("plugins.handmade.man")
require("plugins.handmade.microsoft_windows_open")
require("plugins.handmade.music")
require("plugins.handmade.pki")
require("plugins.handmade.quickfix")
require("plugins.handmade.rappel")
require("plugins.handmade.scratch")
require("plugins.handmade.toggle_autoformat")
require("plugins.handmade.unsaved")
require("plugins.handmade.wiki")
require("plugins.handmade.zet")
require("plugins.handmade.scroll-diff")
require("plugins.handmade.rss")

return {}
